### ISSUE TITLE
[Bug] map组件卸载时取消监听错误

### ISSUE THREAD

**Issue by MangMax** [meteosci/vue-maplibre#1]
你好，我学习了一下源码，发现map组件在unmount时是不是应该取消pitch和move的事件监听，这里是漏改吗

https://github.com/meteosci/vue-maplibre/blob/81757687b42741f7816e95d2f60388670e3dd550/packages/components/map/src/index.ts#L219

https://github.com/meteosci/vue-maplibre/blob/81757687b42741f7816e95d2f60388670e3dd550/packages/components/map/src/index.ts#L220

**Comment by zouyaoji** [comment]
是的哈，感谢！文档搞好了一起更新一下
