### ISSUE TITLE
[Bug] Layer组件重复监听

### ISSUE THREAD

**Issue by MangMax** [meteosci/vue-maplibre#2]
https://github.com/meteosci/vue-maplibre/blob/a64de065663ff96c193ef67a145325795d2b7fb3/packages/components/layer/native/index.ts#L41

https://github.com/meteosci/vue-maplibre/blob/a64de065663ff96c193ef67a145325795d2b7fb3/packages/components/layer/native/index.ts#L56

这里重复监听了layout属性

**Comment by zouyaoji** [comment]
- -都是复制惹的祸。
